# Generated by Django 2.0 on 2017-05-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicy_memes', '0004_auto_20170524_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(default='media/images/image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_field',
            field=models.ImageField(default='media/images/image.jpg', upload_to='images/'),
        ),
    ]
