# Generated by Django 2.0 on 2017-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicy_memes', '0005_auto_20170524_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
